FROM python:3.12

WORKDIR /app

COPY backend/ /app/
COPY backend/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt \
    && pip install --no-cache-dir watchdog \
    && pip install psycopg2-binary \
    && apt-get update && apt-get install -y postgresql-client

EXPOSE 8000

CMD ["sh", "-c", "until pg_isready -h $DATABASE_HOST -p $DATABASE_PORT; do echo waiting for database; sleep 2; done; python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"]
